### ISSUE TITLE
Message on mobile below the screen

### ISSUE THREAD

**Issue by GrimLink** [mooore-digital/magento2-module-add-to-cart-notification#16]
It is better show the addto notification on mobile below, on the screen.
Similar to other mobile notifications as also seen in https://material.io/components/snackbars.

If everyone is okay with this I will create a PR for this

**Comment by GrimLink** [comment]
![Screenshot 2020-09-03 at 11 33 29](https://user-images.githubusercontent.com/4387541/92098299-56e8b980-edd9-11ea-8815-7fa4ab804d47.jpg)

Example DKW

**Comment by orofabio** [comment]
Great suggestion! My only feedback would be to have a little offset on the sides/bottom, lets say 10px or 20px.
